# Generated by Django 4.0.4 on 2022-05-31 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tnp', '0003_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='Boat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=100)),
                ('builder', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('length', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('photo_url', models.TextField()),
            ],
        ),
    ]
